export type Locale = 'ar' | 'en' | 'fr';

export const translations = {
  ar: {
    brand: 'INC ALG 3',
    brandSubtitle: 'منصة رقمنة حاضنة أعمال جامعة الجزائر 3',
    brandFull: 'حاضنة الأعمال لجامعة الجزائر 3 – إبراهيم سلطان شيبوط',
    nav: { home: 'الرئيسية', projects: 'المشاريع', submit: 'قدّم مشروعك', about: 'من نحن', contact: 'اتصل بنا', login: 'دخول', register: 'تسجيل', dashboard: 'لوحة التحكم', admin: 'الإدارة', logout: 'خروج', language: 'اللغة' },
    hero: { title: 'INC ALG 3', subtitle: 'منصة رقمنة حاضنة أعمال جامعة الجزائر 3', description: 'منصة رقمية متكاملة لرقمنة مسار ريادة الأعمال الجامعية — من الفكرة إلى المؤسسة الناشئة', cta1: 'قدّم مشروعك الآن', cta2: 'استعرض المشاريع', marquee: 'من ثروة الأرض النادرة إلى ثروة الأفكار — حاضنة أعمال جامعة الجزائر 3' },
    stats: { submitted: 'مشروع مقدم', accepted: 'مشروع مقبول', evaluating: 'قيد التقييم', startups: 'مؤسسة ناشئة', successRate: 'نسبة النجاح', batches: 'دفعات مدرّبة', incubated: 'مشروع محتضن', projectsRegistered: 'مشروع مسجل' },
    howItWorks: { title: 'كيف تعمل الحاضنة؟', subtitle: 'مسار واضح من الفكرة إلى المؤسسة الناشئة', step1: { title: 'تقديم الفكرة', desc: 'سجّل مشروعك المبتكر عبر المنصة الرقمية' }, step2: { title: 'التقييم والانتقاء', desc: 'لجنة علمية تقيّم المشروع وفق معايير الابتكار والجدوى' }, step3: { title: 'التكوين والمرافقة', desc: 'تكوين مكثف في ريادة الأعمال وإعداد خطة العمل' }, step4: { title: 'تطوير النموذج الأولي', desc: 'بناء نموذج أولي وتسويق المشروع' }, step5: { title: 'التمويل والإطلاق', desc: 'الوصول للتمويل والحصول على وسم المؤسسة الناشئة' } },
    services: { title: 'خدمات الحاضنة', subtitle: 'مرافقة شاملة من الفكرة إلى الإطلاق', s1: { title: 'تكوين في ريادة الأعمال', desc: 'دورات تكوينية في إعداد خطة العمل ودراسة السوق والنمذجة المالية' }, s2: { title: 'مرافقة واتجاه', desc: 'إرشاد من خبراء ومختصين في جميع مراحل المشروع' }, s3: { title: 'تطوير النماذج الأولية', desc: 'دعم تقني لتحويل الفكرة إلى منتج أو خدمة حقيقية' }, s4: { title: 'وسم المؤسسة الناشئة', desc: 'المساعدة في الحصول على وسم "مؤسسة ناشئة" أو "مشروع مبتكر"' }, s5: { title: 'التمويل', desc: 'الربط بصندوق التمويل الوطني الذي يوفّر تمويل بنسبة 100%' }, s6: { title: 'حماية الملكية الفكرية', desc: 'توجيه نحو المعهد الوطني للملكية الصناعية لحماية براءات الاختراع' } },
    about: { title: 'عن الحاضنة', subtitle: 'حاضنة أعمال جامعة الجزائر 3 — IncuBADZ', p1: 'حاضنة أعمال جامعة الجزائر 3 هي خدمة مشتركة للبحث تأسست بموجب الأمر الوزاري المشترك الصادر في 9 يونيو 2022، وتعمل تحت إشراف السيد مدير الجامعة والوصاية المباشرة لوزارة التعليم العالي والبحث العلمي.', p2: 'تسعى الحاضنة إلى مرافقة حاملي المشاريع المبتكرة من الطلبة للحصول على شهادة "مؤسسة ناشئة" أو "براءة اختراع" بموجب القرار الوزاري رقم 1275.', p3: 'تضم جامعة الجزائر 3 – إبراهيم سلطان شيبوط أكثر من 50,000 طالب عبر أربع كليات.', director: 'مدير الحاضنة: د. علي بوعشة محمد', established: 'تأسست: أكتوبر 2020', official: 'الاعتماد الرسمي: يونيو 2022' },
    partners: { title: 'شركاؤنا', subtitle: 'شراكات استراتيجية لدعم الابتكار' },
    cta: { title: 'فكرتك تستحق أكثر من مجرد ورقة', subtitle: 'حوّل فكرتك إلى مؤسسة ناشئة مع حاضنة أعمال جامعة الجزائر 3', button: 'ابدأ رحلتك الآن' },
    footer: { address: '02 شارع أحمد واكد، دالي إبراهيم، الجزائر العاصمة 16000', email: 'incub.alger3@gmail.com', phone: '+213 21 91 04 51', rights: '© 2025 INC ALG 3 — حاضنة أعمال جامعة الجزائر 3. جميع الحقوق محفوظة.', quickLinks: 'روابط سريعة', contactUs: 'اتصل بنا', followUs: 'تابعنا' },
    auth: { loginTitle: 'تسجيل الدخول', registerTitle: 'إنشاء حساب', email: 'البريد الإلكتروني', password: 'كلمة المرور', name: 'الاسم الكامل', phone: 'رقم الهاتف', faculty: 'الكلية', level: 'المستوى الدراسي', loginBtn: 'دخول', registerBtn: 'تسجيل', noAccount: 'ليس لديك حساب؟', hasAccount: 'لديك حساب؟', adminLogin: 'دخول كمسؤول', studentLogin: 'دخول كطالب' },
    faculties: { eco: 'كلية العلوم الاقتصادية والتجارية وعلوم التسيير', info: 'كلية علوم الإعلام والاتصال', pol: 'كلية العلوم السياسية والعلاقات الدولية', sport: 'معهد التربية البدنية والرياضية' },
    levels: { l1: 'السنة الأولى (ليسانس)', l2: 'السنة الثانية (ليسانس)', l3: 'السنة الثالثة (ليسانس)', m1: 'السنة الأولى (ماستر)', m2: 'السنة الثانية (ماستر)', phd: 'دكتوراه' },
    projectsPage: { title: 'المشاريع المقدمة', subtitle: 'استعرض المشاريع المبتكرة المقدمة للحاضنة', submitNew: 'قدّم مشروعاً جديداً', filter: 'تصفية حسب', search: 'ابحث عن مشروع...', all: 'الكل', noProjects: 'لا توجد مشاريع بعد' },
    projectSubmit: { title: 'تقديم مشروع جديد', subtitle: 'أخبرنا عن فكرتك المبتكرة', step1: 'معلومات صاحب المشروع', step2: 'معلومات المشروع', step3: 'الجانب المالي والتقني', step4: 'التأكيد والإرسال', next: 'التالي', prev: 'السابق', submit: 'تقديم المشروع', ownerName: 'الاسم الكامل', email: 'البريد الإلكتروني', phone: 'رقم الهاتف', projectName: 'اسم المشروع', field: 'المجال', description: 'وصف المشروع', problem: 'المشكلة التي يحلها', targetAudience: 'الفئة المستهدفة', addedValue: 'القيمة المضافة', fundingRequired: 'التمويل المطلوب (د.ج)', stage: 'مرحلة المشروع', hasPartner: 'هل يوجد شريك؟', teamSize: 'عدد أفراد الفريق', videoLink: 'رابط الفيديو (اختياري)', success: 'تم تقديم مشروعك بنجاح!', refNumber: 'رقم المرجع', trackProject: 'تتبع مشروعك', submitAnother: 'تقديم مشروع آخر', businessModel: 'نموذج الأعمال التجارية (BMC)', legalFramework: 'الإطار القانوني', tradeName: 'الاسم التجاري', academicYear: 'السنة الجامعية', department: 'القسم' },
    fields: { ict: 'تكنولوجيا المعلومات والاتصال', digital: 'الاقتصاد الرقمي', minerals: 'المعادن النادرة والتعدين', energy: 'الطاقات المتجددة', industry: 'الصناعة والتحويل', ecommerce: 'الخدمات والتجارة الإلكترونية', other: 'أخرى' },
    stages: { idea: 'فكرة', prototype: 'نموذج أولي', launched: 'تم الإطلاق' },
    status: { review: 'قيد المراجعة', committee: 'محال للجنة', accepted: 'مقبول', rejected: 'مرفوض', revision: 'يحتاج تعديل', incubated: 'محتضن' },
    // Admin Dashboard
    admin: { title: 'لوحة الإدارة', overview: 'نظرة عامة', projects: 'المشاريع', users: 'المستخدمون', landing: 'الصفحة الرئيسية', events: 'الأحداث', messages: 'المراسلات', settings: 'الإعدادات', evaluate: 'تقييم', accept: 'قبول', reject: 'رفض', revision: 'طلب تعديل', incubate: 'احتضان', delete: 'حذف', edit: 'تعديل', save: 'حفظ', cancel: 'إلغاء', totalUsers: 'إجمالي المستخدمين', totalProjects: 'إجمالي المشاريع', pendingReview: 'بانتظار المراجعة', acceptedProjects: 'مشاريع مقبولة', landingPage: 'إدارة الصفحة الرئيسية', sectionTitle: 'عنوان القسم', sectionContent: 'محتوى القسم', addImage: 'إضافة صورة', addVideo: 'إضافة فيديو', score: 'التقييم', notes: 'ملاحظات', projectDetails: 'تفاصيل المشروع', backToProjects: 'العودة للمشاريع', editStats: 'تعديل الإحصائيات', statsDesc: 'تحكم في الأرقام المعروضة على الصفحة الرئيسية', recentMessages: 'آخر المراسلات', unread: 'غير مقروءة', reply: 'رد', sendReply: 'إرسال الرد' },
    // Student Dashboard
    student: { title: 'لوحة التحكم', overview: 'نظرة عامة', myProject: 'مشروعي', bmc: 'نموذج الأعمال BMC', messages: 'المراسلات', guide: 'دليل المسار', profile: 'الملف الشخصي', welcome: 'مرحباً', projectStatus: 'حالة المشروع', currentStep: 'الخطوة الحالية', nextSteps: 'الخطوات التالية', sendMessage: 'إرسال رسالة', typeMessage: 'اكتب رسالتك...', adminTeam: 'فريق الإدارة', noProject: 'لم تقم بتقديم مشروع بعد', submitFirst: 'قدّم مشروعك أولاً للمتابعة', stepGuide: { step0: { title: 'تقديم المشروع', desc: 'تم تقديم مشروعك وهو حالياً قيد المراجعة من طرف الإدارة. ستتلقى إشعاراً عند تحديث حالة مشروعك.' }, step1: { title: 'مرحلة المراجعة', desc: 'فريق الإدارة يراجع مشروعك حالياً. تأكد من أن معلوماتك مكتملة وصحيحة.' }, step2: { title: 'التقييم من اللجنة', desc: 'مشروعك تم تحويله للجنة التقييم العلمية. ستتم دعوتك لعرض مشروعك أمام اللجنة.' }, step3: { title: 'القبول والمرافقة', desc: 'تهانينا! مشروعك مقبول. ستبدأ مرحلة التكوين والمرافقة لإكمال نموذج أعمالك.' }, step4: { title: 'تطوير النموذج الأولي', desc: 'الآن عليك تطوير نموذج أولي لمشروعك. استخدم أداة BMC لبناء نموذج أعمالك.' }, step5: { title: 'الاحتضان والإطلاق', desc: 'مشروعك محتضن رسمياً! يمكنك الآن الوصول للتمويل وإطلاق مؤسستك الناشئة.' } } },
    // BMC Tool
    bmc: { title: 'نموذج الأعمال التجاري — BMC', subtitle: 'أداة نموذج الأعمال التجاري وفقاً للقرار الوزاري 1275', keyPartners: 'الشركاء الرئيسيون', keyActivities: 'الأنشطة الرئيسية', keyResources: 'الموارد الرئيسية', valueProposition: 'القيمة المقترحة', customerRelationships: 'العلاقة مع العملاء', channels: 'قنوات التوزيع', customerSegments: 'شرائح العملاء', costStructure: 'هيكل التكاليف', revenueStreams: 'مصادر الإيرادات', placeholder: 'اكتب هنا...', save: 'حفظ BMC', saved: 'تم حفظ BMC بنجاح', toolLink: 'فتح أداة BMC الكاملة (المولد المالي)', toolDesc: 'أداة متكاملة لتوليد الجداول المالية ونموذج الأعمال وفقاً للقرار 1275' },
    // Project Detail
    projectDetail: { overview: 'لمحة عامة', information: 'المعلومات الأساسية', financial: 'الجانب المالي', team: 'الفريق', evaluation: 'التقييم', timeline: 'المسار الزمني', submittedOn: 'تاريخ التقديم', lastUpdate: 'آخر تحديث', refNumber: 'رقم المرجع', noScore: 'لم يتم التقييم بعد' },
    common: { loading: 'جاري التحميل...', save: 'حفظ', cancel: 'إلغاء', delete: 'حذف', edit: 'تعديل', view: 'عرض', close: 'إغلاق', yes: 'نعم', no: 'لا', search: 'بحث', filter: 'تصفية', actions: 'إجراءات', status: 'الحالة', date: 'التاريخ', details: 'التفاصيل', back: 'رجوع', noData: 'لا توجد بيانات' },
  },
  en: {
    brand: 'INC ALG 3', brandSubtitle: 'Digital Platform for University of Algiers 3 Business Incubator', brandFull: 'Business Incubator of University of Algiers 3 – Ibrahim Sultan Cheibout',
    nav: { home: 'Home', projects: 'Projects', submit: 'Submit Project', about: 'About', contact: 'Contact', login: 'Login', register: 'Register', dashboard: 'Dashboard', admin: 'Admin', logout: 'Logout', language: 'Language' },
    hero: { title: 'INC ALG 3', subtitle: 'Digital Platform for University of Algiers 3 Business Incubator', description: 'An integrated digital platform for digitizing the university entrepreneurship journey — from idea to startup', cta1: 'Submit Your Project', cta2: 'Browse Projects', marquee: 'From the rare wealth of the earth to the wealth of ideas — University of Algiers 3 Business Incubator' },
    stats: { submitted: 'Projects Submitted', accepted: 'Accepted Projects', evaluating: 'Under Evaluation', startups: 'Startups Created', successRate: 'Success Rate', batches: 'Trained Batches', incubated: 'Incubated Projects', projectsRegistered: 'Registered Projects' },
    howItWorks: { title: 'How Does the Incubator Work?', subtitle: 'A clear path from idea to startup', step1: { title: 'Submit Your Idea', desc: 'Register your innovative project through the digital platform' }, step2: { title: 'Evaluation & Selection', desc: 'A scientific committee evaluates the project based on innovation and feasibility' }, step3: { title: 'Training & Mentoring', desc: 'Intensive entrepreneurship training and business plan preparation' }, step4: { title: 'Prototype Development', desc: 'Build a prototype and market the project' }, step5: { title: 'Funding & Launch', desc: 'Access funding and obtain the startup label' } },
    services: { title: 'Incubator Services', subtitle: 'Comprehensive support from idea to launch', s1: { title: 'Entrepreneurship Training', desc: 'Training courses in business planning, market research, and financial modeling' }, s2: { title: 'Mentoring & Guidance', desc: 'Guidance from experts and specialists at all project stages' }, s3: { title: 'Prototype Development', desc: 'Technical support to transform the idea into a real product or service' }, s4: { title: 'Startup Labeling', desc: 'Assistance in obtaining "Startup" or "Innovative Project" label' }, s5: { title: 'Funding', desc: 'Connection to the National Startup Fund providing 100% financing' }, s6: { title: 'IP Protection', desc: 'Guidance to INAPI for patent protection' } },
    about: { title: 'About the Incubator', subtitle: 'University of Algiers 3 Business Incubator — IncuBADZ', p1: 'The Business Incubator of University of Algiers 3 is a common research service established by the Interministerial Order of June 9, 2022.', p2: 'The incubator accompanies students with innovative projects to obtain a "Startup Certificate" or "Patent" under Ministerial Decision No. 1275.', p3: 'University of Algiers 3 – Ibrahim Sultan Cheibout has over 50,000 students across four faculties.', director: 'Director: Dr. Ali Bouâcha Mohamed', established: 'Established: October 2020', official: 'Official Accreditation: June 2022' },
    partners: { title: 'Our Partners', subtitle: 'Strategic partnerships to support innovation' },
    cta: { title: 'Your idea deserves more than just paper', subtitle: 'Transform your idea into a startup with the University of Algiers 3 Business Incubator', button: 'Start Your Journey Now' },
    footer: { address: '02 Rue Ahmed Ouaked, Dély Ibrahim, Algiers 16000', email: 'incub.alger3@gmail.com', phone: '+213 21 91 04 51', rights: '© 2025 INC ALG 3 — University of Algiers 3 Business Incubator. All rights reserved.', quickLinks: 'Quick Links', contactUs: 'Contact Us', followUs: 'Follow Us' },
    auth: { loginTitle: 'Sign In', registerTitle: 'Create Account', email: 'Email', password: 'Password', name: 'Full Name', phone: 'Phone Number', faculty: 'Faculty', level: 'Academic Level', loginBtn: 'Sign In', registerBtn: 'Register', noAccount: "Don't have an account?", hasAccount: 'Already have an account?', adminLogin: 'Admin Login', studentLogin: 'Student Login' },
    faculties: { eco: 'Faculty of Economics, Commerce & Management', info: 'Faculty of Information & Communication Sciences', pol: 'Faculty of Political Science & International Relations', sport: 'Institute of Physical Education & Sports' },
    levels: { l1: '1st Year (Bachelor)', l2: '2nd Year (Bachelor)', l3: '3rd Year (Bachelor)', m1: '1st Year (Master)', m2: '2nd Year (Master)', phd: 'Doctorate' },
    projectsPage: { title: 'Submitted Projects', subtitle: 'Browse innovative projects submitted to the incubator', submitNew: 'Submit New Project', filter: 'Filter by', search: 'Search for a project...', all: 'All', noProjects: 'No projects yet' },
    projectSubmit: { title: 'Submit a New Project', subtitle: 'Tell us about your innovative idea', step1: 'Project Owner Information', step2: 'Project Information', step3: 'Financial & Technical', step4: 'Confirmation & Submit', next: 'Next', prev: 'Previous', submit: 'Submit Project', ownerName: 'Full Name', email: 'Email', phone: 'Phone Number', projectName: 'Project Name', field: 'Field', description: 'Project Description', problem: 'Problem Solved', targetAudience: 'Target Audience', addedValue: 'Added Value', fundingRequired: 'Funding Required (DZD)', stage: 'Project Stage', hasPartner: 'Do you have a partner?', teamSize: 'Team Size', videoLink: 'Video Link (optional)', success: 'Your project has been submitted successfully!', refNumber: 'Reference Number', trackProject: 'Track Your Project', submitAnother: 'Submit Another Project', businessModel: 'Business Model Canvas (BMC)', legalFramework: 'Legal Framework', tradeName: 'Trade Name', academicYear: 'Academic Year', department: 'Department' },
    fields: { ict: 'Information & Communication Technology', digital: 'Digital Economy', minerals: 'Rare Minerals & Mining', energy: 'Renewable Energy', industry: 'Industry & Manufacturing', ecommerce: 'Services & E-Commerce', other: 'Other' },
    stages: { idea: 'Idea', prototype: 'Prototype', launched: 'Launched' },
    status: { review: 'Under Review', committee: 'Referred to Committee', accepted: 'Accepted', rejected: 'Rejected', revision: 'Needs Revision', incubated: 'Incubated' },
    admin: { title: 'Admin Panel', overview: 'Overview', projects: 'Projects', users: 'Users', landing: 'Landing Page', events: 'Events', messages: 'Messages', settings: 'Settings', evaluate: 'Evaluate', accept: 'Accept', reject: 'Reject', revision: 'Request Revision', incubate: 'Incubate', delete: 'Delete', edit: 'Edit', save: 'Save', cancel: 'Cancel', totalUsers: 'Total Users', totalProjects: 'Total Projects', pendingReview: 'Pending Review', acceptedProjects: 'Accepted Projects', landingPage: 'Landing Page Management', sectionTitle: 'Section Title', sectionContent: 'Section Content', addImage: 'Add Image', addVideo: 'Add Video', score: 'Score', notes: 'Notes', projectDetails: 'Project Details', backToProjects: 'Back to Projects', editStats: 'Edit Statistics', statsDesc: 'Control the numbers displayed on the landing page', recentMessages: 'Recent Messages', unread: 'Unread', reply: 'Reply', sendReply: 'Send Reply' },
    student: { title: 'Dashboard', overview: 'Overview', myProject: 'My Project', bmc: 'Business Model (BMC)', messages: 'Messages', guide: 'Path Guide', profile: 'Profile', welcome: 'Welcome', projectStatus: 'Project Status', currentStep: 'Current Step', nextSteps: 'Next Steps', sendMessage: 'Send Message', typeMessage: 'Type your message...', adminTeam: 'Admin Team', noProject: 'You haven\'t submitted a project yet', submitFirst: 'Submit your project first to proceed', stepGuide: { step0: { title: 'Project Submission', desc: 'Your project has been submitted and is currently under review. You will be notified when your project status is updated.' }, step1: { title: 'Review Phase', desc: 'The admin team is reviewing your project. Make sure your information is complete and accurate.' }, step2: { title: 'Committee Evaluation', desc: 'Your project has been forwarded to the scientific evaluation committee. You will be invited to present your project.' }, step3: { title: 'Acceptance & Mentoring', desc: 'Congratulations! Your project is accepted. You will begin the training and mentoring phase.' }, step4: { title: 'Prototype Development', desc: 'Now you need to develop a prototype. Use the BMC tool to build your business model.' }, step5: { title: 'Incubation & Launch', desc: 'Your project is officially incubated! You can now access funding and launch your startup.' } } },
    bmc: { title: 'Business Model Canvas — BMC', subtitle: 'Business Model Canvas tool per Ministerial Decision 1275', keyPartners: 'Key Partners', keyActivities: 'Key Activities', keyResources: 'Key Resources', valueProposition: 'Value Proposition', customerRelationships: 'Customer Relationships', channels: 'Channels', customerSegments: 'Customer Segments', costStructure: 'Cost Structure', revenueStreams: 'Revenue Streams', placeholder: 'Type here...', save: 'Save BMC', saved: 'BMC saved successfully!', toolLink: 'Open Full BMC Tool (Financial Generator)', toolDesc: 'Integrated tool for generating financial tables and business model per Decision 1275' },
    projectDetail: { overview: 'Overview', information: 'Basic Information', financial: 'Financial', team: 'Team', evaluation: 'Evaluation', timeline: 'Timeline', submittedOn: 'Submitted On', lastUpdate: 'Last Update', refNumber: 'Reference Number', noScore: 'Not yet evaluated' },
    common: { loading: 'Loading...', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', view: 'View', close: 'Close', yes: 'Yes', no: 'No', search: 'Search', filter: 'Filter', actions: 'Actions', status: 'Status', date: 'Date', details: 'Details', back: 'Back', noData: 'No data available' },
  },
  fr: {
    brand: 'INC ALG 3', brandSubtitle: "Plateforme numérique de l'incubateur d'entreprises de l'Université d'Alger 3", brandFull: "Incubateur d'entreprises de l'Université d'Alger 3 – Ibrahim Sultan Cheibout",
    nav: { home: 'Accueil', projects: 'Projets', submit: 'Soumettre', about: 'À propos', contact: 'Contact', login: 'Connexion', register: 'Inscription', dashboard: 'Tableau de bord', admin: 'Administration', logout: 'Déconnexion', language: 'Langue' },
    hero: { title: 'INC ALG 3', subtitle: "Plateforme numérique de l'incubateur d'entreprises de l'Université d'Alger 3", description: "Une plateforme numérique intégrée pour la numérisation du parcours entrepreneurial universitaire", cta1: 'Soumettez votre projet', cta2: 'Parcourir les projets', marquee: "De la richesse rare de la terre à la richesse des idées — Incubateur de l'Université d'Alger 3" },
    stats: { submitted: 'Projets soumis', accepted: 'Projets acceptés', evaluating: 'En évaluation', startups: 'Startups créées', successRate: 'Taux de réussite', batches: 'Promotions formées', incubated: 'Projets incubés', projectsRegistered: 'Projets enregistrés' },
    howItWorks: { title: "Comment fonctionne l'incubateur ?", subtitle: "Un parcours clair de l'idée à la startup", step1: { title: 'Soumettez votre idée', desc: 'Enregistrez votre projet innovant via la plateforme' }, step2: { title: 'Évaluation & Sélection', desc: "Un comité scientifique évalue le projet selon l'innovation et la faisabilité" }, step3: { title: 'Formation & Accompagnement', desc: 'Formation intensive en entrepreneuriat et préparation du business plan' }, step4: { title: 'Développement du prototype', desc: 'Construisez un prototype et commercialisez le projet' }, step5: { title: 'Financement & Lancement', desc: 'Accédez au financement et obtenez le label startup' } },
    services: { title: "Services de l'incubateur", subtitle: "Un accompagnement complet de l'idée au lancement", s1: { title: 'Formation en entrepreneuriat', desc: 'Cours de formation en planification, étude de marché et modélisation financière' }, s2: { title: 'Mentorat & Orientation', desc: "Conseils d'experts à toutes les étapes du projet" }, s3: { title: 'Développement de prototypes', desc: 'Support technique pour transformer l\'idée en produit ou service réel' }, s4: { title: 'Label Startup', desc: 'Aide à l\'obtention du label "Startup" ou "Projet innovant"' }, s5: { title: 'Financement', desc: 'Connexion au Fonds National des Startups offrant un financement à 100%' }, s6: { title: 'Protection PI', desc: "Orientation vers l'INAPI pour la protection des brevets" } },
    about: { title: "À propos de l'incubateur", subtitle: "Incubateur d'entreprises de l'Université d'Alger 3 — IncuBADZ", p1: "L'incubateur d'entreprises de l'Université d'Alger 3 est un service commun de recherche créé par l'arrêté interministériel du 9 juin 2022.", p2: "L'incubateur accompagne les étudiants porteurs de projets innovants conformément à la Décision ministérielle n°1275.", p3: "L'Université d'Alger 3 – Ibrahim Sultan Cheibout compte plus de 50 000 étudiants.", director: 'Directeur : Dr. Ali Bouâcha Mohamed', established: 'Créé : Octobre 2020', official: 'Accréditation : Juin 2022' },
    partners: { title: 'Nos Partenaires', subtitle: 'Des partenariats stratégiques pour soutenir l\'innovation' },
    cta: { title: 'Votre idée mérite plus qu\'une feuille de papier', subtitle: "Transformez votre idée en startup avec l'incubateur de l'Université d'Alger 3", button: 'Commencez votre parcours' },
    footer: { address: '02 Rue Ahmed Ouaked, Dély Ibrahim, Alger 16000', email: 'incub.alger3@gmail.com', phone: '+213 21 91 04 51', rights: "© 2025 INC ALG 3 — Incubateur de l'Université d'Alger 3. Tous droits réservés.", quickLinks: 'Liens rapides', contactUs: 'Contactez-nous', followUs: 'Suivez-nous' },
    auth: { loginTitle: 'Connexion', registerTitle: 'Créer un compte', email: 'Email', password: 'Mot de passe', name: 'Nom complet', phone: 'Téléphone', faculty: 'Faculté', level: 'Niveau académique', loginBtn: 'Se connecter', registerBtn: "S'inscrire", noAccount: 'Pas de compte ?', hasAccount: 'Déjà un compte ?', adminLogin: 'Connexion admin', studentLogin: 'Connexion étudiant' },
    faculties: { eco: 'Faculté des Sciences Économiques', info: "Faculté des Sciences de l'Information", pol: 'Faculté des Sciences Politiques', sport: 'Institut Éducation Physique' },
    levels: { l1: '1ère année (Licence)', l2: '2ème année (Licence)', l3: '3ème année (Licence)', m1: '1ère année (Master)', m2: '2ème année (Master)', phd: 'Doctorat' },
    projectsPage: { title: 'Projets soumis', subtitle: 'Parcourez les projets innovants', submitNew: 'Soumettre un nouveau projet', filter: 'Filtrer par', search: 'Rechercher un projet...', all: 'Tous', noProjects: 'Aucun projet' },
    projectSubmit: { title: 'Soumettre un nouveau projet', subtitle: 'Parlez-nous de votre idée innovante', step1: 'Informations du porteur', step2: 'Informations du projet', step3: 'Aspects financier & technique', step4: 'Confirmation', next: 'Suivant', prev: 'Précédent', submit: 'Soumettre le projet', ownerName: 'Nom complet', email: 'Email', phone: 'Téléphone', projectName: 'Nom du projet', field: 'Domaine', description: 'Description', problem: 'Problème résolu', targetAudience: 'Public cible', addedValue: 'Valeur ajoutée', fundingRequired: 'Financement requis (DZD)', stage: 'Stade du projet', hasPartner: 'Avez-vous un partenaire ?', teamSize: "Taille de l'équipe", videoLink: 'Lien vidéo (optionnel)', success: 'Projet soumis avec succès !', refNumber: 'Numéro de référence', trackProject: 'Suivre votre projet', submitAnother: 'Soumettre un autre projet', businessModel: 'Business Model Canvas (BMC)', legalFramework: 'Cadre juridique', tradeName: 'Nom commercial', academicYear: 'Année universitaire', department: 'Département' },
    fields: { ict: "Technologies de l'Information", digital: 'Économie numérique', minerals: 'Minéraux rares', energy: 'Énergies renouvelables', industry: 'Industrie', ecommerce: 'E-Commerce', other: 'Autre' },
    stages: { idea: 'Idée', prototype: 'Prototype', launched: 'Lancé' },
    status: { review: 'En révision', committee: 'Transmis au comité', accepted: 'Accepté', rejected: 'Rejeté', revision: 'Modification requise', incubated: 'Incubé' },
    admin: { title: "Panneau d'administration", overview: 'Vue d\'ensemble', projects: 'Projets', users: 'Utilisateurs', landing: "Page d'accueil", events: 'Événements', messages: 'Messages', settings: 'Paramètres', evaluate: 'Évaluer', accept: 'Accepter', reject: 'Rejeter', revision: 'Demander modification', incubate: 'Incuber', delete: 'Supprimer', edit: 'Modifier', save: 'Enregistrer', cancel: 'Annuler', totalUsers: 'Total utilisateurs', totalProjects: 'Total projets', pendingReview: 'En attente', acceptedProjects: 'Projets acceptés', landingPage: "Gestion page d'accueil", sectionTitle: 'Titre de section', sectionContent: 'Contenu', addImage: 'Ajouter image', addVideo: 'Ajouter vidéo', score: 'Score', notes: 'Notes', projectDetails: 'Détails du projet', backToProjects: 'Retour aux projets', editStats: 'Modifier statistiques', statsDesc: "Contrôlez les chiffres affichés sur la page d'accueil", recentMessages: 'Messages récents', unread: 'Non lus', reply: 'Répondre', sendReply: 'Envoyer la réponse' },
    student: { title: 'Tableau de bord', overview: 'Vue d\'ensemble', myProject: 'Mon projet', bmc: 'Modèle affaires (BMC)', messages: 'Messages', guide: 'Guide du parcours', profile: 'Profil', welcome: 'Bienvenue', projectStatus: 'Statut du projet', currentStep: 'Étape actuelle', nextSteps: 'Prochaines étapes', sendMessage: 'Envoyer un message', typeMessage: 'Tapez votre message...', adminTeam: "Équipe d'administration", noProject: "Vous n'avez pas encore soumis de projet", submitFirst: 'Soumettez votre projet pour continuer', stepGuide: { step0: { title: 'Soumission du projet', desc: "Votre projet a été soumis et est en cours de révision. Vous serez notifié de toute mise à jour." }, step1: { title: 'Phase de révision', desc: "L'équipe administrative révise votre projet. Assurez-vous que vos informations sont complètes." }, step2: { title: 'Évaluation du comité', desc: 'Votre projet a été transmis au comité d\'évaluation scientifique.' }, step3: { title: 'Acceptation & Mentorat', desc: 'Félicitations ! Votre projet est accepté. Vous commencerez la formation.' }, step4: { title: 'Développement du prototype', desc: "Développez un prototype. Utilisez l'outil BMC pour construire votre modèle." }, step5: { title: 'Incubation & Lancement', desc: 'Votre projet est officiellement incubé ! Vous pouvez accéder au financement.' } } },
    bmc: { title: 'Business Model Canvas — BMC', subtitle: 'Outil BMC selon la Décision ministérielle 1275', keyPartners: 'Partenaires clés', keyActivities: 'Activités clés', keyResources: 'Ressources clés', valueProposition: 'Proposition de valeur', customerRelationships: 'Relations clients', channels: 'Canaux', customerSegments: 'Segments clients', costStructure: 'Structure des coûts', revenueStreams: 'Sources de revenus', placeholder: 'Écrivez ici...', save: 'Enregistrer BMC', saved: 'BMC enregistré avec succès !', toolLink: 'Ouvrir outil BMC complet', toolDesc: 'Outil intégré pour générer les tableaux financiers selon la Décision 1275' },
    projectDetail: { overview: 'Aperçu', information: 'Informations', financial: 'Financier', team: 'Équipe', evaluation: 'Évaluation', timeline: 'Chronologie', submittedOn: 'Soumis le', lastUpdate: 'Dernière mise à jour', refNumber: 'Numéro de référence', noScore: 'Pas encore évalué' },
    common: { loading: 'Chargement...', save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', edit: 'Modifier', view: 'Voir', close: 'Fermer', yes: 'Oui', no: 'Non', search: 'Rechercher', filter: 'Filtrer', actions: 'Actions', status: 'Statut', date: 'Date', details: 'Détails', back: 'Retour', noData: 'Aucune donnée' },
  },
} as const;

export function t(locale: Locale, path: string): string {
  const keys = path.split('.');
  let result: any = translations[locale];
  for (const key of keys) {
    if (result && typeof result === 'object' && key in result) {
      result = result[key];
    } else {
      return path;
    }
  }
  return typeof result === 'string' ? result : path;
}

export const localeNames: Record<Locale, string> = { ar: 'العربية', en: 'English', fr: 'Français' };
export const localeDirection: Record<Locale, 'rtl' | 'ltr'> = { ar: 'rtl', en: 'ltr', fr: 'ltr' };
