export const MOCK_PROJECTS = [
  { id: 'proj-001', refNumber: 'INC-2025-001', projectName: 'منصة جزائرية للتجارة الإلكترونية', projectNameEn: 'Algerian E-Commerce Platform', projectNameFr: 'Plateforme E-Commerce Algérienne', ownerName: 'أحمد بن علي', ownerEmail: 'ahmed.benali@univ-alger3.dz', ownerPhone: '0555123456', faculty: 'eco', level: 'm2', field: 'ecommerce', description: 'منصة رقمية جزائرية متكاملة للتجارة الإلكترونية تربط المنتجين المحليين بالمستهلكين مباشرة، مع نظام دفع إلكتروني محلي ودعم للغات المتعددة.', problem: 'صعوبة وصول المنتجين المحليين للسوق الرقمي وغياب منصات تجارة إلكترونية محلية موثوقة', targetAudience: 'المنتجون الحرفيون والشركات الصغيرة والمتوسطة في الجزائر', addedValue: 'توفير منصة موحدة تدعم الدفع المحلي وتروج للمنتجات الجزائرية', fundingRequired: 5000000, stage: 'prototype', hasPartner: true, teamSize: 4, status: 'incubated', score: 92, evaluationNotes: 'مشروع مبتكر يخدم الاقتصاد الوطني', legalFramework: 'مؤسسة ناشئة', tradeName: 'DzShop', academicYear: '2024/2025', department: 'علوم التسيير', createdAt: '2025-01-15', timeline: [ { date: '2025-01-15', event: 'تقديم المشروع', eventEn: 'Project Submitted' }, { date: '2025-01-22', event: 'تحويل للجنة التقييم', eventEn: 'Referred to Committee' }, { date: '2025-02-05', event: 'قبول المشروع', eventEn: 'Project Accepted' }, { date: '2025-03-15', event: 'بدء التكوين', eventEn: 'Training Started' }, { date: '2025-05-20', event: 'احتضان المشروع', eventEn: 'Project Incubated' } ] },
  { id: 'proj-002', refNumber: 'INC-2025-002', projectName: 'تطبيق ذكي لإدارة المزارع', projectNameEn: 'Smart Farm Management App', projectNameFr: 'Application Smart Farm', ownerName: 'فاطمة الزهراء مراد', ownerEmail: 'fatima.mourad@univ-alger3.dz', ownerPhone: '0661987654', faculty: 'eco', level: 'm1', field: 'digital', description: 'تطبيق ذكي يستخدم الذكاء الاصطناعي لتحسين إنتاجية المزارع الجزائرية من خلال تحليل البيانات المناخية والتربة.', problem: 'انخفاض إنتاجية القطاع الزراعي بسبب غياب التقنيات الحديثة', targetAudience: 'المزارعون والتعاونيات الفلاحية في الجزائر', addedValue: 'تحسين العائد الزراعي بنسبة تصل إلى 30%', fundingRequired: 8000000, stage: 'prototype', hasPartner: false, teamSize: 3, status: 'accepted', score: 88, evaluationNotes: 'مشروع واعد يخدم الأمن الغذائي الوطني', legalFramework: 'مؤسسة مصغرة', tradeName: 'SmartFarm DZ', academicYear: '2024/2025', department: 'علوم اقتصادية', createdAt: '2025-02-03', timeline: [ { date: '2025-02-03', event: 'تقديم المشروع', eventEn: 'Project Submitted' }, { date: '2025-02-15', event: 'تحويل للجنة التقييم', eventEn: 'Referred to Committee' }, { date: '2025-03-01', event: 'قبول المشروع', eventEn: 'Project Accepted' } ] },
  { id: 'proj-003', refNumber: 'INC-2025-003', projectName: 'نظام ذكي لتتبع المعادن النادرة', projectNameEn: 'Smart Rare Minerals Tracking System', projectNameFr: 'Système de suivi des minéraux rares', ownerName: 'كريم بوزيد', ownerEmail: 'karim.bouzid@univ-alger3.dz', ownerPhone: '0770456789', faculty: 'eco', level: 'l3', field: 'minerals', description: 'نظام رقمي لتتبع وإدارة سلسلة توريد المعادن النادرة في الجزائر، يوفر شفافية كاملة في العمليات التعدينية.', problem: 'غياب الشفافية في سلسلة توريد المعادن النادرة', targetAudience: 'شركات التعدين والهيئات الحكومية', addedValue: 'رقمنة كاملة لسلسلة التوريد مع تقنية البلوكتشين', fundingRequired: 15000000, stage: 'idea', hasPartner: true, teamSize: 5, status: 'committee', score: 85, evaluationNotes: '', legalFramework: 'براءة اختراع', tradeName: 'MinTrack', academicYear: '2024/2025', department: 'علوم تجارية', createdAt: '2025-02-20', timeline: [ { date: '2025-02-20', event: 'تقديم المشروع', eventEn: 'Project Submitted' }, { date: '2025-03-01', event: 'تحويل للجنة التقييم', eventEn: 'Referred to Committee' } ] },
  { id: 'proj-004', refNumber: 'INC-2025-004', projectName: 'منصة تعليمية تفاعلية', projectNameEn: 'Interactive Learning Platform', projectNameFr: 'Plateforme d\'apprentissage interactive', ownerName: 'سارة حداد', ownerEmail: 'sara.haddad@univ-alger3.dz', ownerPhone: '0555345678', faculty: 'info', level: 'm2', field: 'ict', description: 'منصة تعليمية تستخدم الواقع المعزز والذكاء الاصطناعي لتقديم تجربة تعليمية تفاعلية للطلاب الجامعيين.', problem: 'فجوة بين التعليم الأكاديمي ومتطلبات سوق العمل', targetAudience: 'طلاب الجامعات والباحثون عن تطوير المهارات', addedValue: 'دمج التقنيات الحديثة في التعليم مع تخصيص المحتوى للسوق المحلي', fundingRequired: 3000000, stage: 'prototype', hasPartner: false, teamSize: 2, status: 'accepted', score: 90, evaluationNotes: 'حل مبتكر لتحدي حقيقي', legalFramework: 'مؤسسة ناشئة', tradeName: 'EduConnect DZ', academicYear: '2024/2025', department: 'علوم الإعلام', createdAt: '2025-03-01', timeline: [ { date: '2025-03-01', event: 'تقديم المشروع', eventEn: 'Project Submitted' }, { date: '2025-03-10', event: 'قبول المشروع', eventEn: 'Project Accepted' } ] },
  { id: 'proj-005', refNumber: 'INC-2025-005', projectName: 'نظام طاقة شمسية ذكي', projectNameEn: 'Smart Solar Energy System', projectNameFr: 'Système d\'énergie solaire intelligent', ownerName: 'يوسف عمراني', ownerEmail: 'youcef.amrani@univ-alger3.dz', ownerPhone: '0661456789', faculty: 'eco', level: 'm1', field: 'energy', description: 'نظام إدارة ذكي للألواح الشمسية يعتمد على إنترنت الأشياء ويحسن كفاءة إنتاج الطاقة الشمسية بنسبة 25%.', problem: 'انخفاض كفاءة أنظمة الطاقة الشمسية التقليدية', targetAudience: 'الشركات والمؤسسات التي تستخدم الطاقة الشمسية', addedValue: 'تحسين كفاءة الإنتاج وتقليل تكاليف الصيانة', fundingRequired: 12000000, stage: 'idea', hasPartner: true, teamSize: 3, status: 'review', score: null, evaluationNotes: '', legalFramework: 'مشروع مبتكر', tradeName: 'SolarTech DZ', academicYear: '2024/2025', department: 'علوم اقتصادية', createdAt: '2025-03-15', timeline: [ { date: '2025-03-15', event: 'تقديم المشروع', eventEn: 'Project Submitted' } ] },
  { id: 'proj-006', refNumber: 'INC-2025-006', projectName: 'تطبيق السياحة الذكية', projectNameEn: 'Smart Tourism App', projectNameFr: 'Application Tourisme Intelligent', ownerName: 'نور الدين بلال', ownerEmail: 'nour.bilal@univ-alger3.dz', ownerPhone: '0770567890', faculty: 'info', level: 'l3', field: 'digital', description: 'تطبيق سياحي ذكي يقدم تجارب مخصصة للسياح في الجزائر باستخدام الذكاء الاصطناعي والواقع المعزز.', problem: 'ضعف الترويج السياحي الرقمي للمعالم الجزائرية', targetAudience: 'السياح المحليون والدوليون', addedValue: 'تجربة سياحية غنية ومخصصة مع محتوى تفاعلي', fundingRequired: 4000000, stage: 'launched', hasPartner: false, teamSize: 2, status: 'incubated', score: 94, evaluationNotes: 'مشروع متميز يعزز السياحة الوطنية', legalFramework: 'مؤسسة ناشئة', tradeName: 'VisitDZ', academicYear: '2024/2025', department: 'علوم الإعلام', createdAt: '2025-01-20', timeline: [ { date: '2025-01-20', event: 'تقديم المشروع', eventEn: 'Project Submitted' }, { date: '2025-02-01', event: 'قبول المشروع', eventEn: 'Project Accepted' }, { date: '2025-04-15', event: 'احتضان المشروع', eventEn: 'Project Incubated' } ] },
  { id: 'proj-007', refNumber: 'INC-2025-007', projectName: 'روبوت دردشة للخدمات الإدارية', projectNameEn: 'Admin Services Chatbot', projectNameFr: 'Chatbot Services Administratifs', ownerName: 'مريم بلقاسم', ownerEmail: 'meriem.belkacem@univ-alger3.dz', ownerPhone: '0555678901', faculty: 'pol', level: 'm2', field: 'ict', description: 'روبوت دردشة ذكي مخصص للأجهزة الحكومية يوفر خدمات إدارية للمواطنين على مدار الساعة.', problem: 'بطء الإجراءات الإدارية وازدحام المكاتب الحكومية', targetAudience: 'المواطنون والإدارات الحكومية', addedValue: 'رقمنة الخدمات الإدارية وتوفير الوقت والجهد', fundingRequired: 6000000, stage: 'prototype', hasPartner: true, teamSize: 4, status: 'revision', score: 75, evaluationNotes: 'يحتاج تطوير نموذج أولي أكثر تفصيلاً', legalFramework: 'مؤسسة مصغرة', tradeName: 'GovBot DZ', academicYear: '2024/2025', department: 'علوم سياسية', createdAt: '2025-02-10', timeline: [ { date: '2025-02-10', event: 'تقديم المشروع', eventEn: 'Project Submitted' }, { date: '2025-02-25', event: 'طلب تعديل', eventEn: 'Revision Requested' } ] },
  { id: 'proj-008', refNumber: 'INC-2025-008', projectName: 'منصة صناعية ذكية', projectNameEn: 'Smart Industry Platform', projectNameFr: 'Plateforme Industrie Intelligente', ownerName: 'عبد الرحمن شريف', ownerEmail: 'abderrahmane.cherif@univ-alger3.dz', ownerPhone: '0661789012', faculty: 'eco', level: 'l3', field: 'industry', description: 'منصة رقمية لرقمنة العمليات الصناعية في المصانع الجزائرية، تشمل مراقبة الإنتاج والصيانة التنبؤية.', problem: 'تأخر القطاع الصناعي الجزائري في التحول الرقمي', targetAudience: 'المصانع والشركات الصناعية', addedValue: 'تحسين الإنتاجية وتقليل التكاليف التشغيلية بنسبة 20%', fundingRequired: 10000000, stage: 'idea', hasPartner: false, teamSize: 3, status: 'review', score: null, evaluationNotes: '', legalFramework: 'مشروع مبتكر', tradeName: 'IndusSmart', academicYear: '2024/2025', department: 'علوم التسيير', createdAt: '2025-03-20', timeline: [ { date: '2025-03-20', event: 'تقديم المشروع', eventEn: 'Project Submitted' } ] },
  { id: 'proj-009', refNumber: 'INC-2025-009', projectName: 'محفظة إلكترونية جزائرية', projectNameEn: 'Algerian E-Wallet', projectNameFr: 'Portefeuille Électronique Algérien', ownerName: 'ليلى حمداني', ownerEmail: 'leila.hamdani@univ-alger3.dz', ownerPhone: '0770890123', faculty: 'eco', level: 'm1', field: 'ecommerce', description: 'محفظة إلكترونية جزائرية تتيح الدفع والتحويل المالي عبر الهاتف المحمول مع دعم كامل للدينار الجزائري.', problem: 'محدودية حلول الدفع الإلكتروني المحلية', targetAudience: 'المستهلكون والتجار الجزائريون', addedValue: 'حل دفع محلي آمن ومتوافق مع الأنظمة البنكية', fundingRequired: 20000000, stage: 'idea', hasPartner: true, teamSize: 6, status: 'rejected', score: 55, evaluationNotes: 'يحتاج دراسة جدوى أعمق وخطة تنفيذ أوضح', legalFramework: 'مؤسسة مصغرة', tradeName: 'DZPay', academicYear: '2024/2025', department: 'علوم تجارية', createdAt: '2025-01-25', timeline: [ { date: '2025-01-25', event: 'تقديم المشروع', eventEn: 'Project Submitted' }, { date: '2025-02-10', event: 'رفض المشروع', eventEn: 'Project Rejected' } ] },
  { id: 'proj-010', refNumber: 'INC-2025-010', projectName: 'نظام إدارة رياضية جامعي', projectNameEn: 'University Sports Management System', projectNameFr: 'Système de gestion sportive universitaire', ownerName: 'محمد أمين زروال', ownerEmail: 'mohamed.zeroual@univ-alger3.dz', ownerPhone: '0555901234', faculty: 'sport', level: 'm2', field: 'ict', description: 'نظام رقمي متكامل لإدارة الأنشطة الرياضية الجامعية يشمل جدولة المباريات وإدارة الفرق وتتبع الأداء.', problem: 'غياب نظام رقمي موحد للنشاط الرياضي الجامعي', targetAudience: 'معاهد التربية البدنية والجامعات', addedValue: 'رقمنة كاملة للنشاط الرياضي الجامعي مع تحليلات', fundingRequired: 2500000, stage: 'launched', hasPartner: false, teamSize: 2, status: 'incubated', score: 87, evaluationNotes: 'مشروع عملي يخدم قطاعاً مهماً', legalFramework: 'مؤسسة ناشئة', tradeName: 'SportUni DZ', academicYear: '2024/2025', department: 'تربية بدنية', createdAt: '2024-11-10', timeline: [ { date: '2024-11-10', event: 'تقديم المشروع', eventEn: 'Project Submitted' }, { date: '2024-12-01', event: 'قبول المشروع', eventEn: 'Project Accepted' }, { date: '2025-02-15', event: 'احتضان المشروع', eventEn: 'Project Incubated' } ] },
];

export const MOCK_PARTNERS = [
  { id: 'p1', nameAr: 'صندوق تمويل المؤسسات الناشئة', nameEn: 'National Startup Fund', nameFr: 'Fonds National des Startups', logo: '🏦' },
  { id: 'p2', nameAr: 'المركز الجزائري للبحث العلمي', nameEn: 'CERIST', nameFr: 'CERIST', logo: '🔬' },
  { id: 'p3', nameAr: 'الوكالة الوطنية لدعم ريادة الأعمال', nameEn: 'ANADE', nameFr: 'ANADE', logo: '🏢' },
  { id: 'p4', nameAr: 'المعهد الوطني للملكية الصناعية', nameEn: 'INAPI', nameFr: 'INAPI', logo: '📋' },
  { id: 'p5', nameAr: 'وزارة التعليم العالي والبحث العلمي', nameEn: 'MESRS', nameFr: 'MESRS', logo: '🏛️' },
  { id: 'p6', nameAr: 'المديرية العامة للبحث العلمي', nameEn: 'DGRSDT', nameFr: 'DGRSDT', logo: '🔬' },
  { id: 'p7', nameAr: 'مؤسسة السبورة', nameEn: 'El Saboura Foundation', nameFr: 'Fondation El Saboura', logo: '📚' },
  { id: 'p8', nameAr: 'الشبكة الجامعية للحاضنات', nameEn: 'AUNEI', nameFr: 'AUNEI', logo: '🌐' },
];

export const MOCK_EVENTS = [
  { id: 'e1', titleAr: 'ملتقى المؤسسة الناشئة الإفريقية', titleEn: 'African Startup Conference', titleFr: 'Conférence Africaine des Startups', date: '2025-01-15', location: 'قصر الثقافة، الجزائر العاصمة', descAr: 'مشاركة 20 حامل مشروع من جامعة الجزائر 3' },
  { id: 'e2', titleAr: 'اليوم الوطني لريادة الأعمال', titleEn: 'National Entrepreneurship Day', titleFr: 'Journée Nationale de l\'Entrepreneuriat', date: '2025-03-21', location: 'مدرج جامعة الجزائر 3', descAr: 'يوم تحسيسي حول ريادة الأعمال' },
  { id: 'e3', titleAr: 'توقيع اتفاقية شراكة مع CERIST', titleEn: 'Partnership Agreement with CERIST', titleFr: 'Accord de partenariat avec le CERIST', date: '2025-02-05', location: 'رياسة جامعة الجزائر 3', descAr: 'شراكة لدعم التحول الرقمي' },
  { id: 'e4', titleAr: 'تكريم الدفعة 10', titleEn: 'Batch 10 Graduation', titleFr: 'Remise des diplômes - Promotion 10', date: '2025-06-20', location: 'مدرج جامعة الجزعة 3', descAr: 'حفل تكريم المشاريع المقبولة' },
];

export const MOCK_MESSAGES = [
  { id: 'msg-001', from: 'admin-001', fromName: 'المدير العام', fromRole: 'admin' as const, to: 'student-001', text: 'مرحباً أحمد، تم استلام مشروعك وسيتم مراجعته قريباً.', timestamp: '2025-01-16T09:00:00', read: true },
  { id: 'msg-002', from: 'student-001', fromName: 'أحمد بن علي', fromRole: 'student' as const, to: 'admin-001', text: 'شكراً لكم، هل تحتاجون أي معلومات إضافية؟', timestamp: '2025-01-16T10:30:00', read: true },
  { id: 'msg-003', from: 'admin-001', fromName: 'المدير العام', fromRole: 'admin' as const, to: 'student-001', text: 'تم تحويل مشروعك للجنة التقييم. سيتم إبلاغك بالنتيجة.', timestamp: '2025-01-22T14:00:00', read: true },
  { id: 'msg-004', from: 'admin-001', fromName: 'المدير العام', fromRole: 'admin' as const, to: 'student-001', text: 'تهانينا! مشروعك مقبول. يرجى الحضور يوم الاثنين لبدء التكوين.', timestamp: '2025-02-05T11:00:00', read: false },
  { id: 'msg-005', from: 'admin-001', fromName: 'المدير العام', fromRole: 'admin' as const, to: 'student-002', text: 'مرحباً فاطمة، مشروعك قيد المراجعة. سنكون على اتصال قريباً.', timestamp: '2025-02-05T08:00:00', read: true },
  { id: 'msg-006', from: 'student-002', fromName: 'فاطمة الزهراء مراد', fromRole: 'student' as const, to: 'admin-001', text: 'شكراً، أنا متحمسة لمعرفة النتيجة!', timestamp: '2025-02-05T09:15:00', read: true },
];

export const ADMIN_CREDENTIALS = { email: 'admin@univ-alger3.dz', password: 'admin123' };

export const STUDENT_CREDENTIALS = { email: 'ahmed.benali@univ-alger3.dz', password: 'student123' };

export const DEFAULT_BMC = {
  keyPartners: '• موردون\n• هيئات دعم ومرافقة\n• جامعة / حاضنة أعمال',
  keyActivities: '• الإنتاج أو تقديم الخدمة\n• التسويق والبيع\n• خدمة العملاء',
  keyResources: '• تجهيزات واستثمارات\n• موارد بشرية وتقنية\n• معرفة وخبرة الفريق',
  valueProposition: '• تقديم المنتجات والخدمات\n• حل مشكلة محددة للزبائن',
  customerRelationships: '• تواصل مباشر\n• متابعة ودعم\n• خدمة ما بعد البيع',
  channels: '• بيع مباشر\n• شبكات اجتماعية\n• موقع / منصة',
  customerSegments: '• الزبائن المستهدفون\n• السوق المحلي أو الوطني',
  costStructure: '• تكاليف ثابتة شهرية\n• تكاليف متغيرة\n• إهلاكات',
  revenueStreams: '• منتجات وخدمات\n• إيرادات شهرية\n• إيرادات سنوية',
};
