export const MOCK_PROJECTS = [
  {
    id: 'proj-001',
    refNumber: 'INC-2025-001',
    projectName: 'منصة جزائرية للتجارة الإلكترونية',
    projectNameEn: 'Algerian E-Commerce Platform',
    ownerName: 'أحمد بن علي',
    ownerEmail: 'ahmed.benali@univ-alger3.dz',
    ownerPhone: '0555123456',
    faculty: 'eco',
    level: 'm2',
    field: 'ecommerce',
    description: 'منصة رقمية جزائرية متكاملة للتجارة الإلكترونية تربط المنتجين المحليين بالمستهلكين مباشرة، مع نظام دفع إلكتروني محلي ودعم للغات المتعددة.',
    problem: 'صعوبة وصول المنتجين المحليين للسوق الرقمي وغياب منصات تجارة إلكترونية محلية موثوقة',
    targetAudience: 'المنتجون الحرفيون والشركات الصغيرة والمتوسطة في الجزائر',
    addedValue: 'توفير منصة موحدة تدعم الدفع المحلي وتروج للمنتجات الجزائرية',
    fundingRequired: 5000000,
    stage: 'prototype',
    hasPartner: true,
    teamSize: 4,
    status: 'incubated',
    score: 92,
    evaluationNotes: 'مشروع مبتكر يخدم الاقتصاد الوطني',
    createdAt: '2025-01-15',
  },
  {
    id: 'proj-002',
    refNumber: 'INC-2025-002',
    projectName: 'تطبيق ذكي لإدارة المزارع',
    projectNameEn: 'Smart Farm Management App',
    ownerName: 'فاطمة الزهراء مراد',
    ownerEmail: 'fatima.mourad@univ-alger3.dz',
    ownerPhone: '0661987654',
    faculty: 'eco',
    level: 'm1',
    field: 'digital',
    description: 'تطبيق ذكي يستخدم الذكاء الاصطناعي لتحسين إنتاجية المزارع الجزائرية من خلال تحليل البيانات المناخية والتربة وتقديم توصيات دقيقة للمزارعين.',
    problem: 'انخفاض إنتاجية القطاع الزراعي بسبب غياب التقنيات الحديثة',
    targetAudience: 'المزارعون والتعاونيات الفلاحية في الجزائر',
    addedValue: 'تحسين العائد الزراعي بنسبة تصل إلى 30% باستخدام التقنيات الذكية',
    fundingRequired: 8000000,
    stage: 'prototype',
    hasPartner: false,
    teamSize: 3,
    status: 'accepted',
    score: 88,
    evaluationNotes: 'مشروع واعد يخدم الأمن الغذائي الوطني',
    createdAt: '2025-02-03',
  },
  {
    id: 'proj-003',
    refNumber: 'INC-2025-003',
    projectName: 'نظام ذكي لتتبع المعادن النادرة',
    projectNameEn: 'Smart Rare Minerals Tracking System',
    ownerName: 'كريم بوزيد',
    ownerEmail: 'karim.bouzid@univ-alger3.dz',
    ownerPhone: '0770456789',
    faculty: 'eco',
    level: 'l3',
    field: 'minerals',
    description: 'نظام رقمي لتتبع وإدارة سلسلة توريد المعادن النادرة في الجزائر، يوفر شفافية كاملة في العمليات التعدينية ويحسن كفاءة الاستخراج.',
    problem: 'غياب الشفافية في سلسلة توريد المعادن النادرة وضعف التتبع الرقمي',
    targetAudience: 'شركات التعدين والهيئات الحكومية المشرفة على القطاع المعدني',
    addedValue: 'رقمنة كاملة لسلسلة التوريد مع تقنية البلوكتشين للشفافية',
    fundingRequired: 15000000,
    stage: 'idea',
    hasPartner: true,
    teamSize: 5,
    status: 'committee',
    score: 85,
    evaluationNotes: '',
    createdAt: '2025-02-20',
  },
  {
    id: 'proj-004',
    refNumber: 'INC-2025-004',
    projectName: 'منصة تعليمية تفاعلية',
    projectNameEn: 'Interactive Learning Platform',
    ownerName: 'سارة حداد',
    ownerEmail: 'sara.haddad@univ-alger3.dz',
    ownerPhone: '0555345678',
    faculty: 'info',
    level: 'm2',
    field: 'ict',
    description: 'منصة تعليمية تستخدم الواقع المعزز والذكاء الاصطناعي لتقديم تجربة تعليمية تفاعلية للطلاب الجامعيين، مع محتوى مخصص حسب احتياجات سوق العمل الجزائري.',
    problem: 'فجوة بين التعليم الأكاديمي ومتطلبات سوق العمل',
    targetAudience: 'طلاب الجامعات والباحثون عن تطوير المهارات',
    addedValue: 'دمج التقنيات الحديثة في التعليم مع تخصيص المحتوى للسوق المحلي',
    fundingRequired: 3000000,
    stage: 'prototype',
    hasPartner: false,
    teamSize: 2,
    status: 'accepted',
    score: 90,
    evaluationNotes: 'حل مبتكر لتحدي حقيقي في التعليم العالي',
    createdAt: '2025-03-01',
  },
  {
    id: 'proj-005',
    refNumber: 'INC-2025-005',
    projectName: 'نظام طاقة شمسية ذكي',
    projectNameEn: 'Smart Solar Energy System',
    ownerName: 'يوسف عمراني',
    ownerEmail: 'youcef.amrani@univ-alger3.dz',
    ownerPhone: '0661456789',
    faculty: 'eco',
    level: 'm1',
    field: 'energy',
    description: 'نظام إدارة ذكي للألواح الشمسية يعتمد على الإنترنت للأشياء ويحسن كفاءة إنتاج الطاقة الشمسية بنسبة 25% من خلال التتبع الذكي للشمس والصيانة التنبؤية.',
    problem: 'انخفاض كفاءة أنظمة الطاقة الشمسية التقليدية وارتفاع تكاليف الصيانة',
    targetAudience: 'الشركات والمؤسسات التي تستخدم الطاقة الشمسية',
    addedValue: 'تحسين كفاءة الإنتاج وتقليل تكاليف الصيانة بشكل كبير',
    fundingRequired: 12000000,
    stage: 'idea',
    hasPartner: true,
    teamSize: 3,
    status: 'review',
    score: null,
    evaluationNotes: '',
    createdAt: '2025-03-15',
  },
  {
    id: 'proj-006',
    refNumber: 'INC-2025-006',
    projectName: 'تطبيق السياحة الذكية',
    projectNameEn: 'Smart Tourism App',
    ownerName: 'نور الدين بلال',
    ownerEmail: 'nour.bilal@univ-alger3.dz',
    ownerPhone: '0770567890',
    faculty: 'info',
    level: 'l3',
    field: 'digital',
    description: 'تطبيق سياحي ذكي يقدم تجارب مخصصة للسياح في الجزائر باستخدام الذكاء الاصطناعي والواقع المعزز لاكتشاف المعالم التاريخية والثقافية.',
    problem: 'ضعف الترويج السياحي الرقمي للمعالم الجزائرية',
    targetAudience: 'السياح المحليون والدوليون والمكاتب السياحية',
    addedValue: 'تجربة سياحية غنية ومخصصة مع محتوى تفاعلي',
    fundingRequired: 4000000,
    stage: 'launched',
    hasPartner: false,
    teamSize: 2,
    status: 'incubated',
    score: 94,
    evaluationNotes: 'مشروع متميز يعزز السياحة الوطنية',
    createdAt: '2025-01-20',
  },
  {
    id: 'proj-007',
    refNumber: 'INC-2025-007',
    projectName: 'روبوت دردشة للخدمات الإدارية',
    projectNameEn: 'Admin Services Chatbot',
    ownerName: 'مريم بلقاسم',
    ownerEmail: 'meriem.belkacem@univ-alger3.dz',
    ownerPhone: '0555678901',
    faculty: 'pol',
    level: 'm2',
    field: 'ict',
    description: 'روبوت دردشة ذكي مخصص للأجهزة الحكومية يوفر خدمات إدارية للمواطنين على مدار الساعة، يقلل من وقت الانتظار ويحسن جودة الخدمة.',
    problem: 'بطء الإجراءات الإدارية وازدحام المكاتب الحكومية',
    targetAudience: 'المواطنون والإدارات الحكومية',
    addedValue: 'رقمنة الخدمات الإدارية وتوفير الوقت والجهد',
    fundingRequired: 6000000,
    stage: 'prototype',
    hasPartner: true,
    teamSize: 4,
    status: 'revision',
    score: 75,
    evaluationNotes: 'يحتاج تطوير نموذج أولي أكثر تفصيلاً',
    createdAt: '2025-02-10',
  },
  {
    id: 'proj-008',
    refNumber: 'INC-2025-008',
    projectName: 'منصة صناعية ذكية',
    projectNameEn: 'Smart Industry Platform',
    ownerName: 'عبد الرحمن شريف',
    ownerEmail: 'abderrahmane.cherif@univ-alger3.dz',
    ownerPhone: '0661789012',
    faculty: 'eco',
    level: 'l3',
    field: 'industry',
    description: 'منصة رقمية لرقمنة العمليات الصناعية في المصانع الجزائرية، تشمل مراقبة الإنتاج والصيانة التنبؤية وإدارة المخزون باستخدام إنترنت الأشياء.',
    problem: 'تأخر القطاع الصناعي الجزائري في التحول الرقمي',
    targetAudience: 'المصانع والشركات الصناعية في الجزائر',
    addedValue: 'تحسين الإنتاجية وتقليل التكاليف التشغيلية بنسبة 20%',
    fundingRequired: 10000000,
    stage: 'idea',
    hasPartner: false,
    teamSize: 3,
    status: 'review',
    score: null,
    evaluationNotes: '',
    createdAt: '2025-03-20',
  },
  {
    id: 'proj-009',
    refNumber: 'INC-2025-009',
    projectName: 'محفظة إلكترونية جزائرية',
    projectNameEn: 'Algerian E-Wallet',
    ownerName: 'ليلى حمداني',
    ownerEmail: 'leila.hamdani@univ-alger3.dz',
    ownerPhone: '0770890123',
    faculty: 'eco',
    level: 'm1',
    field: 'ecommerce',
    description: 'محفظة إلكترونية جزائرية تتيح الدفع والتحويل المالي عبر الهاتف المحمول مع دعم كامل للدينار الجزائري وتوافق مع الأنظمة البنكية المحلية.',
    problem: 'محدودية حلول الدفع الإلكتروني المحلية في الجزائر',
    targetAudience: 'المستهلكون والتجار الجزائريون',
    addedValue: 'حل دفع محلي آمن ومتوافق مع الأنظمة البنكية الجزائرية',
    fundingRequired: 20000000,
    stage: 'idea',
    hasPartner: true,
    teamSize: 6,
    status: 'rejected',
    score: 55,
    evaluationNotes: 'المشروع يحتاج دراسة جدوى أعمق وخطة تنفيذ أكثر وضوحاً',
    createdAt: '2025-01-25',
  },
  {
    id: 'proj-010',
    refNumber: 'INC-2025-010',
    projectName: 'نظام إدارة رياضية جامعي',
    projectNameEn: 'University Sports Management System',
    ownerName: 'محمد أمين زروال',
    ownerEmail: 'mohamed.zeroual@univ-alger3.dz',
    ownerPhone: '0555901234',
    faculty: 'sport',
    level: 'm2',
    field: 'ict',
    description: 'نظام رقمي متكامل لإدارة الأنشطة الرياضية الجامعية يشمل جدولة المباريات وإدارة الفرق وتتبع الأداء الرياضي.',
    problem: 'غياب نظام رقمي موحد لإدارة الأنشطة الرياضية الجامعية',
    targetAudience: 'معاهد التربية البدنية والجامعات',
    addedValue: 'رقمنة كاملة للنشاط الرياضي الجامعي مع تحليلات الأداء',
    fundingRequired: 2500000,
    stage: 'launched',
    hasPartner: false,
    teamSize: 2,
    status: 'incubated',
    score: 87,
    evaluationNotes: 'مشروع عملي يخدم قطاعاً مهماً',
    createdAt: '2024-11-10',
  },
];

export const MOCK_STATS = {
  totalSubmitted: 1800,
  accepted: 245,
  underEvaluation: 380,
  startupsCreated: 130,
  successRate: 72,
  trainedBatches: 11,
  incubatedProjects: 610,
  projectsRegistered: 1800,
};

export const MOCK_PARTNERS = [
  { id: 'p1', nameAr: 'صندوق تمويل المؤسسات الناشئة', nameEn: 'National Startup Fund', nameFr: 'Fonds National des Startups', logo: '🏦' },
  { id: 'p2', nameAr: 'المركز الجزائري للبحث العلمي والمعلومات', nameEn: 'CERIST', nameFr: 'CERIST', logo: '🔬' },
  { id: 'p3', nameAr: 'الوكالة الوطنية لدعم ريادة الأعمال', nameEn: 'ANADE', nameFr: 'ANADE', logo: '🏢' },
  { id: 'p4', nameAr: 'المعهد الوطني للملكية الصناعية', nameEn: 'INAPI', nameFr: 'INAPI', logo: '📋' },
  { id: 'p5', nameAr: 'وزارة التعليم العالي والبحث العلمي', nameEn: 'MESRS', nameFr: 'MESRS', logo: '🏛️' },
  { id: 'p6', nameAr: 'المديرية العامة للبحث العلمي', nameEn: 'DGRSDT', nameFr: 'DGRSDT', logo: '🔬' },
  { id: 'p7', nameAr: 'مؤسسة السبورة', nameEn: 'El Saboura Foundation', nameFr: 'Fondation El Saboura', logo: '📚' },
  { id: 'p8', nameAr: 'الشبكة الجامعية للحاضنات ومراكز ريادة الأعمال', nameEn: 'AUNEI', nameFr: 'AUNEI', logo: '🌐' },
];

export const MOCK_EVENTS = [
  {
    id: 'e1',
    titleAr: 'ملتقى المؤسسة الناشئة الإفريقية',
    titleEn: 'African Startup Conference',
    titleFr: 'Conférence Africaine des Startups',
    date: '2025-01-15',
    location: 'قصر الثقافة، الجزائر العاصمة',
    descAr: 'مشاركة 20 حامل مشروع من جامعة الجزائر 3 في الملتقى الإفريقي للمؤسسات الناشئة',
  },
  {
    id: 'e2',
    titleAr: 'اليوم الوطني لريادة الأعمال',
    titleEn: 'National Entrepreneurship Day',
    titleFr: 'Journée Nationale de l\'Entrepreneuriat',
    date: '2025-03-21',
    location: 'مدرج جامعة الجزائر 3',
    descAr: 'يوم تحسيسي حول ريادة الأعمال وفرص إنشاء المؤسسات الناشئة',
  },
  {
    id: 'e3',
    titleAr: 'توقيع اتفاقية شراكة مع CERIST',
    titleEn: 'Partnership Agreement Signing with CERIST',
    titleFr: 'Signature d\'accord de partenariat avec le CERIST',
    date: '2025-02-05',
    location: 'رياسة جامعة الجزائر 3',
    descAr: 'توقيع اتفاقية شراكة مع المركز الجزائيري للبحث لدعم التحول الرقمي',
  },
  {
    id: 'e4',
    titleAr: 'تكريم الدفعة 10 من الحاضنة',
    titleEn: 'Batch 10 Graduation Ceremony',
    titleFr: 'Cérémonie de remise des diplômes - Promotion 10',
    date: '2025-06-20',
    location: 'مدرج جامعة الجزائر 3',
    descAr: 'حفل تكريم المشاريع المقبولة من الدفعة العاشرة وتسليم الشهادات',
  },
];

export const ADMIN_CREDENTIALS = {
  email: 'admin@univ-alger3.dz',
  password: 'admin123',
};
